### ISSUE TITLE
Wondering how to do filterByFormula

### ISSUE THREAD

**Issue by pastorryanhayden** [Airtable/airtable-ruby#22]
I've spent a lot of time with the Node version of this, and I'm wondering if there is a way to do filterByFormula.  A simple example would be really nice.

For instance, I'm wondering if there is something like this:

```ruby
@table = @client.table("MyAppID", "Movies")
@records = @table.records(:sort => ["weekend_at", :desc], :limit => 100, :filterByFormula => 'Live')
```
Thanks in advance

**Comment by sbauch** [comment]
There's an instance method `select` on table.

https://github.com/Airtable/airtable-ruby/blob/master/lib/airtable/table.rb#L31

```
@table = @client.table("MyAppID", "Movies")
@records = @table.select(limit: 10, sort: ["Name", "asc"], formula: "Rating > 65")
```
