### ISSUE TITLE
Add support for searching 

### ISSUE THREAD

**Issue by syrnick** [Airtable/airtable-ruby#4]
This is more of a heads up that we pushed out new API capabilities. https://github.com/Airtable/airtable.js/commit/08e6e76902168baa1881aacca35b5cea861d7679

We now accept a formula to filter records and an array of fields/direction pairs to sort by.

The limit is deprecated in favor of pageSize and maxRecords.

**Comment by nesquena** [comment]
Nice! Had been hoping to see implement for a while, thanks!

**Comment by sbauch** [comment]
I'd be happy to work on this as I currently need this feature set.

@syrnick I'm having trouble finding docs on the formulas for filtering.

Something like `Order > 4` is easy enough, but right now I'm looking to find multiple records by ID with one lookup.

So something like `id IS rec12343 OR id IS rec56789` throws an error - 

```
{
  "error": {
    "type": "INVALID_FILTER_BY_FORMULA",
    "message": "The formula for filtering records is invalid: please check your formula text."
  }
}
```

Where can I find the docs that dictate a valid formula?

**Comment by syrnick** [comment]
Here's a few pointers: 
https://support.airtable.com/hc/en-us/articles/202576519-Guide-to-formula-lookup-count-and-rollup-fields

https://support.airtable.com/hc/en-us/articles/203255215-Formula-Field-Reference

You should also be able to do something like this

```
AND(RECORD_ID() = 'recXYZ1', RECORD_ID() = 'recXYZ2', RECORD_ID() = 'recXYZ3', RECORD_ID() = 'recXYZ4')
```

Depending on performance, we'll eventually add a separate endpoint for something like this or optimize this specific call or add a different operator to check record ID against an array.

**Comment by sbauch** [comment]
Great, thanks @syrnick 

Looks like the official JS lib only checks that the formula is in fact a string and depends on the API for validating the formula itself, so I'll take that same approach here.

**Comment by syrnick** [comment]
This was done by @sbauch .
